apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: demo-ingress
spec:
rules:
- host: sales.learnitguide.net
http:
paths:
- backend:
serviceName: Sales-svc
servicePort: 80
- host: purchase.learnitguide.net
http:
paths:
- backend:
serviceName: Purchase-svc
servicePort: 80
- host: examples.site1.com
http:
paths:
- backend:
serviceName: Examples-svc
servicePort: 80
